:toc: left

= System Requirements 1

== Stuff
`[being organized...]`

https://youtu.be/fgqt9SrqKfs

* Requirement vs. Implementation | What vs. How


* One thought
* Concise
* Positive statement
* Unambiguous
* Verifiable.  Inspection, analysis, demonstration, or test.

Terminology
* Shall - requirement
* Will - facts or declaration of purpose
* Should - goal


* *ize and *ly

Minimize use of:

* all
* any
* each
* every
* intent
* it
* these
* this



BEFORE writing requirements:

* Define: need, goals, and objectives
* Identify all stakeholders
* Identify drivers, constraints, dependencies
* Document assumptions


Eliciting requirements:

* Operational concepts.  A day in the life...
* User stories





// //////////////////////////////////////////////


* Give each requirement a unique identifier (QRA 3).
  This makes referring to other requirements simple and clear.
* Standardize your requirements document language (QRA 4).
  Shall, must, wi




=== Functional vs. non-functional

[horizontal]
Functional::  What the system *does*.  Use form "`The [device] _shall_ [verb] ...`"


[horizontal]
Non-functional:: Performance or constraints.  Use "`__must__`"



=== Implementation-neutral

* Clearly states what the system must _do_ and _not how_ it does it.

* Stated in terms of _external interfaces_, or behaviors that can be readily
_observed_ (therefore measured).



=== Verifiable

How can this requirement item be satisfied?

* 


=== Directives

Use of Tables or other references instead of embedding in English sentences.

[quote]
____
*3.2.5.4 Emergency Lighting* +
The CTS shall provide automatically activated emergency lighting for crew
egress and operational recovery in accordance with Table 3.2.5.4-1. [R.CTS.044]
____



=== Weak words

about,
acceptable,
accommodate,
adequate,
"`and/or`",
appropriate,
as allowed,
as directed,
be able to,
compatible,
desirable,
durable,
easy,
effective,
efficient,
enhance,
essential,
optimum,
possible,
practical,
reasonable,
relevant,
reliable,
robust,
significant,
heavy duty,
hereinafter,
high,
if possible,
dependable,
industrial grade,
insufficient,
intent,
low,
maximize,
minimize,
necessary,
normal,
powerful,
smooth,
strict,
sufficient,
suitable,
user friendly,
various,





== Due before class

What vs. how

== During class
"Requirements Bingo"


=== R1
The Crew Transport System (CTS) need to provide continuous autonomous launch abort capability from lift-off through orbital insertion with a 95% probability of success with at least 90% confidence in the event of a loss of thrust or loss of attitude control.

=== R2
No hot surfaces should be present on the outside surface of the heater.

=== R3
The wheelchair must support one person’s weight and, when folded, must easily fit in the trunk of a car.

=== R4
The motorcycle gas mileage must be at least 60 mpg.

=== R5
The device shall not disturb any object with a mass greater than 2 kg.

=== R6
The robot must not come within 10 inches of the wall.

=== R7
The self-contained bin on the device shall have a volume around 125 L.

=== R8
The software interface should be user friendly and use the Terasic display.

=== R9
The device shall not consume more than 500 W average power in normal running state, measured over a time interval of one second.

=== R10
In normal running state, the device shall generate less noise than a running car.

=== R11
No external surface of the device shall exceed 25 degrees Celsius in temperature otherwise the system should use a fan to reduce its temperature.

=== R12
The suit shall accommodate crew metabolic loads provided in Appendix F - Metabolic Loads during all flight phases while maintaining a good core body temperature.

=== R13
The spacecraft shall be enhanced to protect the crew from any impact force.

=== R14
The device shall be powered by 120VAC electricity.





== Reference

link:docs/21_Tips_for_Writing_Exceptionally_Clear_Requirements.pdf[QRA: 21 Tips for Writing Exceptionally Clear Requirements^]

link:docs/Requirement-Experts-Reference-Card-merged-for-web-site.pdf[Requirements
Experts: Reference Card^]




