:toc: auto
:sectnums:
:sectanchors:



= ECE 212: The Design Process for Electrical and Computer Engineers

A study of the design process as it relates to electrical and computer engineering.
All steps of the design process will be considered in depth, and students will complete both incremental projects and a comprehensive design project that integrates their knowledge of the course material with technical design constraints.

1 cr.
Prerequisites: ECE 221, ECE 251, and ECE 263.


== Learning Objectives

// use these anchors to reference the course-level objectives in the week-level
// items like  <<LO-4>>
1. [[LO-1]] Explain the engineering design process.

2. [[LO-2]] Perform all steps of the engineering design process.
 
3. [[LO-3]] Design a solution to meet specified needs within realistic constraints.

4. [[LO-4]] Work effectively as a member of a team.

5. [[LO-5]] Recognize ethical and professional responsibilities in engineering situations.



== Schedule
Sub-section numbers are the class session / week numbers.

https://docs.google.com/spreadsheets/d/1lhiTP_FWcWIptPWG0bhi009jbC8wNhC_0vyd-29lNwA/edit?usp=sharing[Schedule mapping class number to dates for each section^]


=== Introduction -- Design Process
http://www.kennethkuhn.com/students/the%20science%20of%20design.htm[The Science of Design - Kenneth Kuhn^]

==== Due before class
The 0-credit deadline is before class 2, but best done right away.

* [ ] Signup for a Slack account at https://valpo-engr.slack.com/signup

==== During class
> Design is seeing a thing that does not yet exist and making it happen.

* Course introduction and brief syllabus review.
*

==== After class
Find 




=== System Requirements 1
https://youtu.be/fgqt9SrqKfs

* EARS -- Easy Approach to Requirements Syntax
* Requirement vs. Implementation | What vs. How

==== Due before class
Read EARS resource

What vs. how

==== During class

==== After class


=== System Requirements 2
"Requirements Bingo"

<<LO-1>>

==== Due before class

==== During class

==== After class



=== Team Meetings


=== Design Reviews


==== An Introduction to Design Reviews - Kenneth Kuhn
http://www.kennethkuhn.com/students/design%20reviews.htm[An Introduction to Design Reviews - Kenneth Kuhn^]




=== Realistic Constraints

=== Solution Evaluation
Define the meaning of "`best`".

=== Minimum Viable Prototype

=== Testing and Verification

=== Process Improvement

=== Professional Responsiblilities

https://en.wikipedia.org/wiki/Engineering_ethics

https://www.ieee.org/about/corporate/governance/p7-8.html[IEEE code of ethics]

https://www.edn.com/electronics-blogs/the-noble-profession/4238028/The-IEEE-Code-of-Ethics[EDN - The IEEE Code of Ethics]

https://www.computer.org/web/education/code-of-ethics



=== 


=== 


=== 


// vim: tw=0
