:toc: left
:sectnums:
:sectanchors:


= ECE 212: Syllabus

The Design Process for Electrical and Computer Engineers


== Information

A study of the design process as it relates to electrical and computer engineering.
All steps of the design process will be considered in depth, and students will complete both incremental projects and a comprehensive design project that integrates their knowledge of the course material with technical design constraints.

[horizontal]
Credits:: 1 cr.
Prerequisites:: ECE 221, ECE 251, and ECE 263


== Learning Objectives

// use these anchors to reference the course-level objectives in the week-level
// items like  <<LO-perform>>
1. [[LO-explain]] Explain the engineering design process.

2. [[LO-perform]] Perform all steps of the engineering design process.
 
3. [[LO-constraints]] Design a solution to meet specified needs within realistic constraints.

4. [[LO-team]] Work effectively as a member of a team.

5. [[LO-ethics]] Recognize ethical and professional responsibilities in engineering situations.



== Logistics

=== Instructors
Dan White (Monday, Wednesday)::
* dan.white@valpo.edu
* Slack: `@prof-white`
* Office: GEM 205

Georges El-Howayek (Friday)::
* georges.el-howayek@valpo.edu
* Slack: `@prof.howayek`
* Office: GEM 109

=== Location and Time
[horizontal]
Location:: GEM 166

// prevent merging ^ and v together
* *Section A* -- 8:00 AM Monday
* *Section B* -- 8:00 AM Wednesday
* *Section C* -- 8:00 AM Friday

https://docs.google.com/spreadsheets/d/1lhiTP_FWcWIptPWG0bhi009jbC8wNhC_0vyd-29lNwA/edit?usp=sharing[This spreadsheet maps the session number to date for each section^].

*Note:* you must pay attention to the specific weekly schedule for _your section_ only.
Because of the various University no-classes days, your classmates in other sections may be up to 2 weeks ahead or behind your section at any particular moment.


=== Google Classroom
Instead of Blackboard for this course, each section will use Google Classroom for assignments, announcements, and links to extra resources.

Go to https://classroom.google.com[^] (login to your Valpo Google account if necessary) and click on the &oplus; in the upper-right.
Use the code for your specific section to join.
This also creates a G-Calendar for the course.

.Google Classroom course codes
[options="autowidth"]
|===
| Section   | Code

| A  | `1tyf8g`
| B  | `64bzpx`
| C  | `uu5qhhp`
|===


=== Slack
Course-wide discussion and questions will use the chat application Slack.
The College of Engineering has our own workspace (https://valpo-engr.slack.com[`valpo-engr.slack.com`]) which keeps all of your CoE-related channels in the same account for convenience.
You may request to have new channels added to consolidate other engineering course or organization channels.

https://valpo-engr.slack.com/signup[Slack signup^] for an account.



== Grading


.Score weighting
|===
| Category          | Percentage

| Guided practice   | 30
| Homework          | 30
| Project           | 40
|===


.The following percentages on the weighted score for the semester will guarantee the letter grades shown.
|===

| &ge; 93    | A
| &ge; 90    | A-
| &ge; 87    | B+
| &ge; 83    | B
| &ge; 80    | B-
| &ge; 77    | C+
| &ge; 73    | C
| &ge; 70    | C-
| &ge; 67    | D+
| &ge; 63    | D
| &ge; 60    | D-
| &lt; 60  | F
|===




== Honor Code
> I have neither given or received, nor have I tolerated others' use of unauthorized aid.

This statement is written on all homework, quizzes and exams at Valparaiso University.
Every student must write it out the Honor Code in full and sign it for all work submitted for academic credit.
It expresses the promise of the student not to cheat through action or inaction.
This allows unproctored examinations and expresses the faith of the faculty in the student body.

The student initiated Honor System, administered by the Honor Council and its constituent bodies, is recognized and approved by Valparaiso University as an integral part of the regulations under which students in the undergraduate colleges become members of the university community.
Therefore, it is impossible for anyone to become a member of the university without both explicit and implicit adherence to the Honor System.

Every student has the responsibility to keep academics free of dishonesty, that is, to neither give or receive unauthorized aid.
Non-toleration of the use of unauthorized aid is a further responsibility that is inherent in the Honor System.
Each student must report to the Honor Council any violation of the System of which the student becomes aware, free from the pressure of ensuing penalty. 

*Remember, it shall be the responsibility of the student, when in doubt, to ask the instructor what is or is not authorized aid.*

For more information: http://www.valpo.edu/student/honorcouncil




== Access and Accommodataion
The Access & Accommodations Resource Center (AARC) is the campus office that works with students to provide access and accommodations in cases of diagnosed mental or emotional health issues, attentional or learning disabilities, vision or hearing limitations, chronic diseases, or allergies.
You can contact the office at aarc@valpo.edu or 219.464.5206.
Students who need, or think they may need, accommodations due to a diagnosis, or who think they have a diagnosis, are invited to contact AARC to arrange a confidential discussion with the AARC office.
Further, students who are registered with AARC are required to contact their professor(s) if they wish to exercise the accommodations outlined in their letter from the AARC.


== Class Cancellation Policy
Notifications of class cancellations will be made through Blackboard with as much advance notice as possible.
It will be both posted on Blackboard and sent to your Valpo e-mail address.
If you don't check your Valpo e-mail account regularly or have it set-up to be forwarded to your preferred e-mail account, you may not get the message.
Please check Blackboard and your Valpo e-mail (or the e-mail address it forwards to) before coming to class.



// vim: tw=0
